Kubernetes logging
otus-kuber-2020-07/LinarNadyrov_platform pull request #11
Opened 2020-09-20 12:42 UTC by LinarNadyrov

# Выполнено ДЗ №

 - [x] Установил EFK и Grafana
 - [x] Самостоятельное задание | Установка nginx-ingress
 - [x] Установил nginx ingress
 - [x] Настроил node exporters

## В процессе сделано:
 - [x] Установил EFK и Grafana
 - [x] Самостоятельное задание | Установка nginx-ingress
 - [x] Установил nginx ingress
 - [x] Настроил node exporters

## Как запустить проект:

## Как проверить работоспособность:

## PR checklist:
 - [x] Выставлен label с темой домашнего задания

2020-09-23 14:51 UTC, Jasstkn requested changes
С точки зрения конфигурации все верно. Можете поднять кластер еще раз и дать мне ссылку на кибану? попробую потраблшутить

2020-09-23 20:07 UTC, LinarNadyrov commented
@Jasstkn да хорошо. Завтра подниму кластер и раскатаю все, что нужно. 
Как будет все готово напишу в Slack

2020-09-27 05:15 UTC, LinarNadyrov commented
@Jasstkn просьба посмотреть PR и сделать APPROVE

2020-09-27 13:43 UTC, Jasstkn approved these changes
Добрый день! 
Теперь все верно, здорово, что мы с вами разобрались :)
Успехов с другими домашками!

2020-09-27 13:43 UTC, merged

2020-09-27 17:29 UTC, LinarNadyrov commented
Спасибо Вам большое :-)