Kubernetes operators
otus-kuber-2020-07/LinarNadyrov_platform pull request #15
Opened 2020-11-08 13:23 UTC by LinarNadyrov

# Выполнено ДЗ №

 - [x] Основное ДЗ

## В процессе сделано:
 - Напишем CustomResource и CustomResourceDefinition для mysql оператора
 - Соберем образ и сделаем деплой оператора

## Как запустить проект:
 - Описание в README

## Как проверить работоспособность:
 - Описание в README

## PR checklist:
 - [x] Выставлен label с темой домашнего задания

2020-11-11 18:28 UTC, Jasstkn requested changes
Добрый день. Оставила фидбек - обратите внимание на ошибку в тестах!

2020-11-11 18:28 UTC, Jasstkn commented on kubernetes-operators/deploy/cr.yml
> +usless_data: "useless info"
Нужно убрать эту секцию из кастом ресурса - в тестах не проходит валидация.

2020-11-11 18:29 UTC, LinarNadyrov commented on kubernetes-operators/deploy/cr.yml
> +usless_data: "useless info"
Вот эту ?
usless_data: "useless info"

2020-11-11 18:38 UTC, Jasstkn commented on kubernetes-operators/deploy/cr.yml
> +usless_data: "useless info"
Да)

2020-11-12 15:01 UTC, LinarNadyrov commented on kubernetes-operators/deploy/cr.yml
> +usless_data: "useless info"
Готово :-)

2020-11-13 06:47 UTC, Jasstkn approved these changes
Добрый день. Все сделано верно - аппрув 👍

2020-11-13 06:47 UTC, merged